import QueryClientProvider from "@/components/QueryClientProvider";
import SessionProvider from "@/components/SessionProvider";
import "@/css/satoshi.css";
import "@/css/style.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <QueryClientProvider>
      <html lang="en">
        <body suppressHydrationWarning={true}>
          <SessionProvider session={session}>
            <div className="dark:bg-boxdark-2 dark:text-bodydark">
              {children}
            </div>
          </SessionProvider>
        </body>
      </html>
    </QueryClientProvider>
  );
}
